language: c++

before_install:
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - sudo apt-get install g++-multilib gcc-multilib
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  #- haxelib install openfl > /dev/null
  - git clone --recursive https://github.com/openfl/openfl ~/openfl --depth 1
  - haxelib dev openfl ~/openfl
  - git clone --recursive https://github.com/openfl/lime ~/lime --depth 1
  - haxelib dev lime ~/lime
  - haxelib install lime > /dev/null
  - haxelib install hxcpp > /dev/null
  - haxelib install actuate > /dev/null
  - haxelib install box2d > /dev/null
  - haxelib install swf > /dev/null
  - haxelib install layout > /dev/null
  - haxelib install format > /dev/null
  - haxelib dev openfl-samples $(pwd)
  - haxelib run lime rebuild linux -release -64 -nocffi > log.txt || cat log.txt
  - haxelib run lime rebuild tools -nocffi

script:
  - haxelib run openfl create ActuateExample
  - haxelib run openfl create AddingAnimation
  - haxelib run openfl create AddingText
  - haxelib run openfl create BunnyMark
  - haxelib run openfl create DisplayingABitmap
  - haxelib run openfl create HandlingKeyboardEvents
  - haxelib run openfl create HandlingMouseEvents
  - haxelib run openfl create HerokuShaders
  - haxelib run openfl create PiratePig
  - haxelib run openfl create PlayingSound
  - haxelib run openfl create SimpleBox2D
  - haxelib run openfl create SimpleOpenGLView
  - haxelib run openfl create SimpleSWFLayout
  - haxelib run openfl build $(pwd)/ActuateExample flash
  - haxelib run openfl build $(pwd)/AddingAnimation flash
  - haxelib run openfl build $(pwd)/AddingText flash
  - haxelib run openfl build $(pwd)/BunnyMark neko
  - haxelib run openfl build $(pwd)/DisplayingABitmap flash
  - haxelib run openfl build $(pwd)/HandlingKeyboardEvents flash
  - haxelib run openfl build $(pwd)/HandlingMouseEvents flash
  - haxelib run openfl build $(pwd)/HerokuShaders neko
  - haxelib run openfl build $(pwd)/PiratePig flash
  - haxelib run openfl build $(pwd)/PlayingSound flash
  - haxelib run openfl build $(pwd)/SimpleBox2D flash
  - haxelib run openfl build $(pwd)/SimpleOpenGLView neko
  - haxelib run openfl build $(pwd)/SimpleSWFLayout flash

notifications:
  slack: openfl:ba3HbgtZflW8TNcJEQ1B4tAY
