version: 2
jobs:
  
  build:
    docker:
     - image: openfl/openfl-tests-unit-3.4:0.0.3
    steps:
     - checkout
     - run: git clone --recursive https://github.com/openfl/openfl ~/openfl --depth 1
     - run: haxelib dev openfl ~/openfl
     - run: git clone --recursive https://github.com/openfl/lime ~/lime --depth 1
     - run: haxelib dev lime ~/lime
     - run: cp ~/lime/templates/bin/lime.sh /usr/local/bin/lime
     - run: haxelib install hxp
     - run: haxelib install box2d
     - run: haxelib install layout
     - run: haxelib dev openfl-samples ~/project
     - run: haxelib run lime rebuild linux -release -64 -nocffi > log.txt || cat log.txt
     - run: haxelib run lime rebuild tools -nocffi
     - run: haxelib run hxp build all html5
     - run: haxelib run hxp build all flash
     - run: haxelib run hxp build all neko
     - run: haxelib run hxp build all cpp
  
workflows:
  version: 2
  
  build:
    jobs:
     - build